version: '3.8'

services:
  app:
    build: .
    image: latansabima/internify-web
    container_name: internify-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: internifyweb
      DB_USERNAME: root
      DB_PASSWORD: 
    volumes:
      - .:/var/www

  mysql:
    image: mysql:8.0
    container_name: internify-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: internifyweb
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: