version: '3.8'

services:
  app:
    image: latansabima/internify-web:latest
    container_name: internify-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: internifyweb
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./env/.env:/var/www/.env

  mysql:
    image: mysql:8.0
    container_name: internify-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: internifyweb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: internify-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  mysql-data:
