@extends('user.layout.master')
@section('content')
    @include('user.component.navbar')
    @include('user.component.hero')
    @include('user.component.about')
    @include('user.component.informasi')
    @include('user.component.panduan')
    @include('user.component.footer')
@endsection