name: Check Monitoring & Auto-Recovery

on:
  schedule:
    - cron: '*/60 * * * *'  # Setiap 10 menit
  workflow_dispatch:        

jobs:
  check-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Buat file private key
        run: |
          echo "${{ secrets.VPS_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Cek status container monitoring di VPS
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
            echo "Cek monitoring stack..."

            missing=$(docker ps --format "{{.Names}}" | grep -E "grafana|prometheus|cadvisor" | wc -l)
            
            if [ "$missing" -lt 3 ]; then
              echo "Salah satu container tidak jalan, mencoba restart..."
              docker-compose -f /opt/monitoring/docker-compose.yml up -d

              sleep 10

              running=$(docker ps --format "{{.Names}}" | grep -E "grafana|prometheus|cadvisor" | wc -l)
              if [ "$running" -lt 3 ]; then
                echo "Monitoring masih gagal setelah restart, kirim alert ke Bot Telegram"
                curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                  -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
                  -d text="*Monitoring di VPS gagal dijalankan setelah restart.* Periksa segera!" \
                  -d parse_mode="Markdown"
                exit 1
              else
                echo "Monitoring berhasil dipulihkan."
              fi
            else
              echo "Semua container monitoring aktif."
            fi
          '

      - name: Hapus key
        run: rm -f key.pem
