name: CI/CD Laravel Docker to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/internify-web:latest
            ${{ secrets.DOCKER_USERNAME }}/internify-web:${{ github.sha }}

      - name: Sync docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "docker-compose.yml"
          target: "/var/www/internify-web"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            echo "[1] Pulling latest image from Docker Hub"
            docker pull ${{ secrets.DOCKER_USERNAME }}/internify-web:latest

            echo "[2] Stopping and removing existing Laravel container (if any)"
            docker stop internify-app || true
            docker rm internify-app || true

            echo "[3] Recreate Laravel container with updated image"
            docker-compose -f /var/www/internify-web/docker-compose.yml up -d app

            echo "[4] Optimize Laravel config and migrate database"
            docker exec internify-app php artisan config:clear
            docker exec internify-app php artisan migrate --force

            echo "[5] Set permission for storage and cache"
            docker exec internify-app chmod -R 775 storage bootstrap/cache