name: CI/CD Laravel Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/internify-web:latest
      
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/internify-web:latest
            # Cek dan hapus container jika ada
            if [ "$(docker ps -a -q -f name=internify-app)" ]; then
              docker stop internify-app
              docker rm internify-app
            else
              echo "No existing container"
            fi
            # Jalankan docker-compose
            docker-compose -f var/www/internify-web/docker-compose.yml up -d --build