name: CI/CD Laravel Docker to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env file for Docker
        run: |
          cat <<EOF > .env
APP_NAME=${{ secrets.APP_NAME }}
APP_ENV=local
APP_KEY=${{ secrets.APP_KEY }}
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=${{ secrets.DB_DATABASE }}
DB_USERNAME=${{ secrets.DB_USERNAME }}
DB_PASSWORD=${{ secrets.DB_PASSWORD }}

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME=${{ secrets.APP_NAME }}

EOF


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/internify-web:latest
            ${{ secrets.DOCKER_USERNAME }}/internify-web:${{ github.sha }}

      - name: Sync docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "docker-compose.yml"
          target: "/var/www/internify-web"


      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            echo "[1] Pulling latest image from Docker Hub"
            docker pull ${{ secrets.DOCKER_USERNAME }}/internify-web:latest

            echo "[2] Stopping and removing existing Laravel container (if any)"
            docker stop internify-app || true
            docker rm internify-app || true

            echo "[3] Recreate Laravel container with updated image"
            docker-compose -f /var/www/internify-web/docker-compose.yml up -d

            echo "[4] Running Laravel optimize + migrate + seed"
            docker exec internify-app php artisan config:clear
            docker exec internify-app php artisan migrate --force
            docker exec internify-app php artisan db:seed --force
