name: Laravel Tests

on:
  push:
      branches:
        - main
      pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: internifyweb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysql
          tools: composer
 
      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Create .env.testing
        run: |
          echo "${{ secrets.ENV_TESTING }}" > .env.testing

      - name: Generate APP Key
        run: php artisan key:generate --env=testing

      - name: Run Migrations
        run: php artisan migrate --env=testing --force

      - name: Run PHP Unit Tests
        run: php artisan test

      - name: Start Chrome Driver
        run: php artisan dusk:chrome-driver

      - name: Run Laravel Dusk Tests
        run: php artisan dusk
        env:
          APP_URL: http://localhost:8000
          DB_HOST: 127.0.0.1