name: Laravel PHPUnit Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: internifyweb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, zip, bcmath

      - name: Copy .env.testing
        run: |
          echo "APP_ENV=testing" >> .env.testing
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env.testing
          echo "APP_DEBUG=true" >> .env.testing
          echo "APP_URL=http://localhost" >> .env.testing
          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=127.0.0.1" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=internifyweb" >> .env.testing
          echo "DB_USERNAME=root" >> .env.testing
          echo "DB_PASSWORD=root" >> .env.testing
          echo "CACHE_DRIVER=array" >> .env.testing
          echo "SESSION_DRIVER=array" >> .env.testing
          echo "QUEUE_CONNECTION=sync" >> .env.testing

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run migrations
        run: php artisan migrate --env=testing --force

      - name: Run Seeding
        run: php artisan db:seed --env=testing --force

      - name: Run PHPUnit tests
        run: php artisan test --env=testing
